### ISSUE TITLE
About page: move Related web pages to the last section

### ISSUE THREAD

**Issue by vdeparday** [Vizzuality/openDRI#102]
Related Web Pages should be the last section in that page.

**Comment by apercas** [comment]
Hello, this issue is in conflict with this other one: https://github.com/Vizzuality/openDRI/issues/49 Where should it go? Thanks.

**Comment by vdeparday** [comment]
It can be contact and then related webpages.

**Comment by apercas** [comment]
Done: http://dev-gfdrr-opendri.pantheonsite.io/about/

**Comment by vdeparday** [comment]
I still see in the same place but anyway I will try to fix those directly on Monday when I have time to dig into a bit more.
