### ISSUE TITLE
Projects Map: Country Popups - Uneven spacing in metadata

### ISSUE THREAD

**Issue by rsoden** [Vizzuality/openDRI#181]
On the projects map, when there are multiple pillars in a country, the spacing between pillar names is uneven in the country pop-up.  Here are two screenshots in Chrome on Mac from Sri Lanka and Indonesia. Nepal is another example.

<img width="341" alt="screen shot 2016-08-03 at 4 29 27 pm" src="https://cloud.githubusercontent.com/assets/130505/17384188/7bd73364-5997-11e6-817e-93dc6c9d84c5.png">
<img width="356" alt="screen shot 2016-08-03 at 4 29 22 pm" src="https://cloud.githubusercontent.com/assets/130505/17384189/7be37dae-5997-11e6-8c5e-b3b6e5a61966.png">

**Comment by apercas** [comment]
Fixed.

**Comment by shanikadhettige** [comment]
@apercas Cleared cache just in case and used different browsers. Error is less obvious but not fixed, see Indonesia as example
![indonesiaprojectboxerror](https://cloud.githubusercontent.com/assets/17725960/17700999/0564355c-6396-11e6-8af4-9bf4a5fe5918.png)

**Comment by apercas** [comment]
Updated.
